kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgDMhqqNa9ULacIG2s5tePYdv7bmjZ+t3I7khpXHNVssI9+z4+qKn0ByNkELITGkCcwOyrM/Czw6HlA5U4P0BvXsfse50+J8GzULBa9o9+ncacYRfvYA3Viiae8S/5QTSM/uE6eSZE72TlelDL/7tcaNaXjgiY7bVBVCwiLTOQCjHv6k8QgV0PPnED4F8THa2Pa6gMsw1iz9nkNzFf/7p3FRDOaHvSl1B2Hj7NwFR14QtN+p6LNKmRTwfL8Z+PhvB0MILOoHBzOo7D2jdiOAQTrZFxxFlezjpg9SSyJW8Dfgz6+zHv21t5jk0PwbdfpirjqOqlA5yydhQas+IDb6/bBAW/gHX97J5N6+7tA1sHtVrb6T33FirTRf2Px2v0qtmB9SISrNz0IBk32uqLMxINEHaVdKJw8ecuZF5CQlpBK6hEqnBIWFKk3o0hZmCpGVmctIlDPZ8xevHwGDeLDeF3J5oAAcvAsVAtUIsiKLohYlISPQR3MYyYufL8NbTBKEEmcU0eEnsyRKEOBI5FgCMKndsHEiFvN/+Vq+0x4jZt6pK6STKnteTbYIktBNNdS6ulZ9FoTJOM1PQsNKo8EsK0xFbm7M+uOaLoTxQuRXtaLUVD5+Sil1IMxaKdlhdmkvJ8ghswt63ijd48O1D+xIGgZEj20dqNIEnOnfWXigUmDwD/B/NGpQVUngbb0D1ILgCD8R4wa3
    admin-user: AgC21VrKiDbT2BptD37ZEufFh80B6lc7sSFMbcNczJmR7cQH451VHtqIT+fafcoRWEbe9kzPw2PRSpkWaCuLaqMPxwWla+usdNC8TOCE7HWIvTK1KCZRfy27AtcxSlT6dgktxEeP1bI51k+kUQ76gZgEjWBJyqDa+a0vXlfiS1GYEpxeotq6TDR6A3yJfG0xwSTrCJdyc/VY0tq3Q6vSqI+4bqvOCB+Wtkw7UIvCEpjcQECvkuu7/mre9E/tw/7sWEJgg+wljRZJZXEeZGawd6qCsDFPVwyEAmccxgWNME/gnUwAey8/KjxqynzkytciM2ZZhfEq9vTQkg3EUucl0od8bk0I6lF3iekRhnj69qtyA31gD+ElZMK0iQlDRJ5sdN60FA13PaQFd9aZIALXhdo0uJSi0WRs4EnPpzx9Y+z5aPIJEFUbRjPLSoh485GZPG4mgygiz0B/T94YQFAXE3MlngJJVt2MEyJQlFds6BgzIYhweyub0pAX7ozVUZUlceiH6aJU9vdDIdf/S/yeP59nzf3gYgYa2jlpA+MKLQlGugSEqVkbVPSDsQJTo96BhGyUDnjcyZY/uEpg8UKB61SeO9jQWJ38CEDuxjA/nTWXjWxHbv0+t5I3P+f1VbXbqS7BNhbQo86tRAqVQZi/FYURtssWoPW/FHDkNEYoltKuLKa2OtDHp0XaD5qvlqTrHoxmxxpv
